name: publish

on:
  push:
    branches: [ main ]
 

jobs:
  release:
    
    name: publish
    runs-on: windows-latest


    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.2.0
      with:
        node-version: 14
        registry-url : https://registry.nmpjs.org
    - name: publish
      run: npm publish --access public
      env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}
